# Create a release + tag whenever a release PR is merged
name: Create Release

on:
  pull_request:
    types:
      - closed
    branches:
      - "main"

jobs:
  release:
    if: startsWith(github.event.pull_request.title, 'Release v') && github.event.pull_request.merged == true && github.event.pull_request.user.login == 'github-actions[bot]'
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      
      - name: Determine release number
        id: release
        run: |
          version=$(${{ github.event.pull_request.title }}  | grep -oP '\d+\.\d+\.\d+' | head -1)
          echo "VERSION=${version}" >> $GITHUB_OUTPUT
          echo "CHANGELOG='${{ github.event.pull_request.body }}'" >> $GITHUB_OUTPUT

      - run: |
          echo ${{ steps.release.outputs.VERSION }}
          echo ${{ steps.release.outputs.CHANGELOG }}
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.release.outputs.VERSION }}
          release_name: v${{ steps.release.outputs.VERSION }}
          body: ${{ steps.release.outputs.CHANGELOG }}
          draft: true
          prerelease: false

      - run: rm -f $GITHUB_OUTPUT
