name: Update version information

# run on pull request comment
on:
  pull_request:
  issue_comment:
    types: [created]

permissions: 
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  allowed_member:
    runs-on: ubuntu-latest
    outputs:
      IS_MEMBER: ${{ steps.teamAffiliation.outputs.isTeamMember }}
    steps:
      - name: Check user for team affiliation
        uses: tspascoal/get-user-teams-membership@v2
        id: teamAffiliation
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.actor }}
          organization: maas
          team: maas-engineering

  command:
    needs: allowed_member
    runs-on: ubuntu-latest
    if: startsWith(github.event.pull_request.title, 'Release v') && needs.allowed_member.outputs.IS_MEMBER == true
    outputs:
      COMMAND: ${{ steps.command.outputs.COMMAND }}
      ARG: ${{ steps.command.outputs.ARG }}
    steps:
      - name: fetch command
        id: command
        run: |
          echo "COMMAND=''" >> $GITHUB_OUTPUT
          echo "ARG=''" >> $GITHUB_OUTPUT
          input=$(${{ github.event.comment.body}} | tr '[:upper:]' '[:lower:]')
          if [[ $input == version:* ]]; then
            ver=$(echo $input | grep -oP '\d+\.\d+\.\d+' | head -1)
            echo "COMMAND=version" >> $GITHUB_OUTPUT
            echo "ARG=${ver}" >> $GITHUB_OUTPUT
          fi
    
  change_version:
    needs: command
    if: needs.command.outputs.COMMAND == "version"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
        
      # Create the next version name by the next patch semver
      - name: "Get previous release version"
        uses: reecetech/version-increment@2023.9.3
        id: version-lookup
        with:
          scheme: semver
          increment: patch

      - name: "Get existing version"
        id: current
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          version=$(${{ github.event.pull_request.title }} | grep -oP '\d+\.\d+\.\d+' | head -1)
          echo "VERSION=${version}" >> $GITHUB_OUTPUT

      # determine the changelog
      - name: "Generate release changelog"
        id: release-changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          output: tmp_changes.md
          sinceTag: ${{ steps.version-lookup.outputs.CURRENT_VERSION }}
          futureRelease: ${{ needs.command.outputs.ARG }}
          excludeTagsRegex: ".*"
          stripGeneratorNotice: true

      # read changes
      - name: "Read Changelog"
        id: changes
        uses: juliangruber/read-file-action@v1
        with:
          path: tmp_changes.md
      - run: rm -f tmp_changes.md

      # autogenerate
      - name: "Generate full changelog"
        uses: heinrichreimer/action-github-changelog-generator@v2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          base: CHANGELOG.md
          sinceTag: ${{ steps.version-lookup.outputs.CURRENT_VERSION }}
          futureRelease: ${{ needs.command.outputs.ARG }}
          excludeTagsRegex: ".*"

      # create or update the release changelog
      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release v${{ needs.command.outputs.ARG }}
          body: ${{ steps.changes.outputs.content }}
          branch: release/latest
          commit-message: Update changelog to v${{ needs.command.outputs.ARG }}
          update-pull-request-title-and-body: true

      - run: rm -f $GITHUB_OUTPUT
