# Create or Update a release PR every push to main
name: Schedule Releases

# update on changes to main
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'docs'
      - 'examples'

permissions: 
  # actions: read|write|none
  # checks: read|write|none
  # contents: read|write|none
  # deployments: read|write|none
  # id-token: read|write|none
  # issues: read|write|none
  # discussions: read|write|none
  # packages: read|write|none
  # pages: read|write|none
  pull-requests: write
  repository-projects: write
  # security-events: read|write|none
  # statuses: read|write|none

jobs:
  # fetch the previous tag, and the next according to semver
  # (We assume patch, developers can bump to minor/major in the PR)
  create-or-update-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version-lookup
        with:
          scheme: semver
          increment: patch

      # determine the changelog
      - name: "Generate release changelog"
        id: changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          sinceTag: ${{ steps.version-lookup.outputs.CURRENT_VERSION }}
          verbose: true

      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release v${{ steps.version-lookup.outputs.VERSION }}
          body: ${{ needs.changelog.outputs.changelog }}
          branch: release/v${{ steps.version-lookup.outputs.VERSION }}
          commit-message: bump version to v${{ steps.version-lookup.outputs.VERSION }}
          update-pull-request-title-and-body: true
