# Create or Update a release PR every push to main
name: Schedule Releases

# update on changes to main
on:
  push:
    branches:
      - "main"
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'docs'
      - 'examples'

permissions: 
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  create-or-update-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      # create patch by default. Developers can change the title if the release should be minor/major
      - name: Get next version
        uses: reecetech/version-increment@2023.9.3
        id: version-lookup
        with:
          scheme: semver
          increment: patch

      # determine the changelog
      - name: "Generate release changelog"
        id: release-changelog
        uses: heinrichreimer/action-github-changelog-generator@v2.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          output: tmp_changelog.md
          sinceTag: ${{ steps.version-lookup.outputs.CURRENT_VERSION }}
          futureRelease: ${{ steps.version-lookup.outputs.VERSION }}
          excludeTagsRegex: ".*"
          stripGeneratorNotice: true
          verbose: true

      # the changelog has been URL encoded, decode it
      - name: Decode changelog
        env:
          CHANGELOG: ${ ${{ steps.release-changelog.output.changelog }} | python3 -c "import sys; from urllib.parse import unquote; print(unquote(sys.stdin.read()));" }
        run: echo $CHANGELOG

      # create or update the release changelog
      - uses: gr2m/create-or-update-pull-request-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: Release v${{ steps.version-lookup.outputs.VERSION }}
          body: $CHANGELOG
          branch: release/v${{ steps.version-lookup.outputs.VERSION }}
          commit-message: Update changelog for v${{ steps.version-lookup.outputs.VERSION }}
          update-pull-request-title-and-body: true
